### ISSUE TITLE
Utworzenie struktury katalogów

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#10]
CO:
Zostanie utworzona struktura katalogów:
bananaTapChallenge/frontend/iphone
bananaTapChallenge/backend
bananaTapChallenge/documentation

DLACZEGO:
Realizacja

DoD:
Struktura katalogów zostanie dostarczona na repozytorium na do katalogu root

**Comment by 83997** [comment]
Zrobione
