### ISSUE TITLE
[iPhone] Implementacja widoku Statystyk

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#16]
DoR:
Aplikacja ScoreStorage dostępna na środowisku Testowym

Co:
Implementacja widoku statystyk na podstawie dostarczonych mockup'ów 
mockup'y znajdują się w katalogu documentation
Dokumentacja API backend znajduje się w katalogu documentation

Dlaczego:
Realizacja

DoD:
Aplikacja wyświetla statystyki top10 i wynik użytkownika

**Comment by andrej4321** [comment]
issue 16 

Cel testu: 
Implementacja widoku statystyk z wykorzystaniem dostarczonych mockup'ów

Oczekiwana watość:
Pobieranie i wyświetlanie 10 największych wartości przypisanych do tokenów. 

Wartość testowa
Wyświetlanie w statystyk 10 najlepszych wyników.

Status
Aplikacja DZIAŁA, umożliwia zobaczenie 10 najlepszych wyników które wyświetlają się na wmockup' ach.
