### ISSUE TITLE
[iPhone] Implementacja samplowania banana

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#17]
DoR:
Aplikacja ScoreStorage dostępna na środowisku Testowym

Co:
Implementacja samplowania banana
Dokumentacja API backend znajduje się w katalogu documentation

Dlaczego:
Realizacja

DoD:
Aplikacja wysyła do aplikacji ScoreStorage sample z uderzeń w banana

**Comment by andrej4321** [comment]
issue 17 

Cel testu: 
Implementacja samplowania banana


Wartość testowa:
Aplikacja wysyła do aplikacji ScoreStorage sample z uderzeń w banana

Status: 
Aplikacja DZIAŁA, umożliwia wysyła do ScoreStorage sample z uderzeń umożliwiając liczenie punktów.
