### ISSUE TITLE
[iPhone] Implementacja widoku Rozgrywki

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#18]
Co:
Implementacja widoku rozgrywki na podstawie dostarczonych mockup'ów
mockup'y znajdują się w katalogu documentation

Dlaczego:
Realizacja

DoD:
Aplikacja wyświetla banana, a po jego uderzeniu wykonuje się animacja potrząsania i wypadania punktów, wypadanie punktów zależne od szybkości klikania.

**Comment by andrej4321** [comment]
issue 18
DZIAŁA 

Cel testu:	
Przetestowanie implementacji widoku rozgrywki na podstawie mockup'ów  
Aplikacja reaguje na klikanie w wizerunek banana 


Oczekiwania wartość: 
naliczanie punktów związanych z kliknięciem połączone z animacją drgania banana


Status: 
Aplikacja DZIAŁA prawidłowo, wyświetla punkty oraz uruchamia znimację związane z kliknięciami w wizerunek banana
