### ISSUE TITLE
[iPhone] Implementacja uwierzytelniania

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#19]
DoR:
Aplikacja ScoreStorage dostępna na środowisku Testowym

Co:
Implementacja  uwierzytelniania urządzenia z serwisem ScoreStorage
Aplikacja przy pierwszym uruchomieniu wyświetla widok z inputem do wpisania nicku, aplikacja wysyła żądanie na serwis ScoreStorage o wygenerowanie unikalnego token'a. Aplikacja zapisuje klucz w urządzeniu, Token będzie wykorzystywany do wysyłania sampli i pobieranie ilości punktów.

Dokumentacja API v2 backend znajduje się w katalogu documentation
Mock na Projekt_SAN/bananaTapChallenge/documentation/24.pdf

Dlaczego:
Realizacja

DoD:
Aplikacja zapisuje otrzymany token i nazwę użytkownika

**Comment by andrej4321** [comment]
issue 19

DZIAŁA 

Cel testu: 
Przetestowanie uwierzytelnienia urządzenia z serwisem ScoreStorage. 
Aplikacja przy pierwszym uruchomieniu wyświetla widok z inputem do wpisania nicku, aplikacja wysyła żądanie na serwis ScoreStorage o wygenerowanie unikalnego token'
Unikalny Token dla urządzenia wykorzystywany do wysyłania sampli i pobierania ilości punktów. 

Oczekiwana wartość: 
przydzielanie odpowiedniego tokenu oraz nazwy użytkownika 

Wartość testowa: 
Zapisywanie w serwisie wartości dla tokenu. 

Status: 
Aplikacja DZIAŁA, umożliwia wpisanie nazwy gracza i odpowiedniego tokenu.
