### ISSUE TITLE
[ScoreStorage] Implementacja endpoint'u uwierzytelniania

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#20]
DoR:
Dokumentacja API

Co:
Implementacja endpoint'u uwierzytelniania

Dokumentacja API backend znajduje się w katalogu documentation

Dlaczego:
Realizacja

DoD:
aplikacja na żądanie generuje token który zapisuje do bazy danych

**Comment by klkornacki** [comment]
@andrej4321 aby przetestować aplikację należy uruchomić bazę postgres i uruchomić aplikację gradlew.bat bootRun i w przeglądarce wywołać localhost:8080/v1/token/generate

Powinien wygenerować się json z tokenem, następnie należy sprawdzić czy w bazie danych powstała tabela "device" i w niej rekord z token z wyniku zapytania

Wszystko jest opisane w pliku README.md projektu score-storage

**Comment by Maciaszekanies** [comment]
https://github.com/83997/Projekt_SAN/tree/master/bananaTapChallenge/backend/score-storage

**Comment by andrej4321** [comment]
issue 20
DZIAŁA 

Cel testu:	
Przetestowanie Implementacji enpointu'u uwierzytelnienia (wersja z dnia 7.05.19) 
Aplikacjaa na żadanie generuje token i zapisuje go w bazie danych

Akcja:
Po uprzednim zainstalowaniu pgadmin  możemy prześledzić całą procedurę 
Wchodzimy po przez konsolę do projektu score-storage.
Następnie wpisujemy polecenie-  gradlew.bat bootRun 
Sprawdzamy poprawność operacji w pgAdmin

Oczekiwania wartość: losowo stworzony token

Wartość testowa: losowo otrzymany token który zzostał zapisany w bazie danych

Status: Aplikacja DZIAŁA prawidłowo, generuje token  i zapisuje go w bazie danych. 
![p11](https://user-images.githubusercontent.com/50059165/57581555-7d366780-74b9-11e9-90a2-dc90a9c46ac0.png)
![p111](https://user-images.githubusercontent.com/50059165/57581556-80315800-74b9-11e9-8778-3abebcf2d008.png)
![p1111](https://user-images.githubusercontent.com/50059165/57581559-8c1d1a00-74b9-11e9-9114-155a8e3f30b7.png)
