### ISSUE TITLE
[ScoreStorage] Implementacja endpoint'u samplowania

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#21]
DoR:
Dokumentacja API

Co:
Implementacja endpoint'u samplowania

Dokumentacja API backend znajduje się w katalogu documentation

Dlaczego:
Realizacja

DoD:
aplikacja na żądanie zapisuje sampl z rozgrywki w bazie danych

**Comment by klkornacki** [comment]
@andrej4321 aby przetestować aplikację należy uruchomić bazę postgres i uruchomić aplikację gradlew.bat bootRun i wywołać localhost:8080/v1/sample/save metodą POST (najlepiej użyć POSTMANA, należy uzupełnić body względem dokumentacji api)

Powinien wygenerować się json z przyznanymi punktami, następnie należy sprawdzić czy w bazie danych powstała tabela "sample" i w niej rekord z wynikiem

Wszystko jest opisane w pliku README.md projektu score-storage

**Comment by Maciaszekanies** [comment]
https://github.com/83997/Projekt_SAN/tree/master/bananaTapChallenge/backend/score-storage

**Comment by andrej4321** [comment]
issue 21
SĄ BŁĘDY

Cel testu:	
Przetestowanie Implementacji enpointu'u SAMPLOWANIA (wersja z dnia 7.05.19) 
Aplikacja na zadanie podaje wynik w odpowiedzi na ilość kliknięć i czas jaki to zabrało. 

Akcja:
Po uprzednim zainstalowaniu pgadmin  możemy prześledzić całą procedurę 
Wchodzimy po przez konsolę do projektu score-storage.
Następnie wpisujemy polecenie-  gradlew.bat bootRun 
Dalszą część najlepiej prześledzić z dzięki programowi Postman i wykorzystaniu metody POST.

Oczekiwania wartość: wynik który jest odpowiedzią na ilość kliknięć i czas jaki to zajęło

Wartość testowa: losowo otrzymany token który został zapisany w bazie danych

Status: W Aplikacji występują BŁĘDY, nie nadaje punktów przy małej ilości kliknięć w stosunku do dużych jednostek czasu.
	Przy większej ilości kliknięć lub krótkim czasie gry błąd nie występuje.
![isuu21wykrytyblad](https://user-images.githubusercontent.com/50059165/57581649-9390f300-74ba-11e9-9500-e2f308c41af4.png)
