### ISSUE TITLE
[ScoreStorage] Implementacja endpoint'u statystyk top

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#22]
DoR:
Dokumentacja API

Co:
Implementacja endpoint'u statystyk top

Dokumentacja API backend znajduje się w katalogu documentation

Dlaczego:
Realizacja

DoD:
aplikacja na żądanie zwraca top najlepszych wyników

**Comment by klkornacki** [comment]
@andrej4321 aby przetestować aplikację należy uruchomić bazę postgres i uruchomić aplikację gradlew.bat bootRun i wywołać w przeglądarce http://localhost:8080/v1/score/top

Powinien wygenerować się json z top punktami, następnie należy sprawdzić czy w bazie danych powstała tabela "sample" i punkty się zgadzają
np. SELECT sum(score) FROM public.sample GROUP BY fk_device_id ORDER BY sum DESC LIMIT 2;

Wszystko jest opisane w pliku README.md projektu score-storage

**Comment by Maciaszekanies** [comment]
https://github.com/83997/Projekt_SAN/tree/master/bananaTapChallenge/backend/score-storage

**Comment by andrej4321** [comment]
![projek22a](https://user-images.githubusercontent.com/50059165/57581731-0353ad80-74bc-11e9-8312-c92debf7bf9d.png)
![projek22](https://user-images.githubusercontent.com/50059165/57581733-03ec4400-74bc-11e9-9890-a25cfc708515.png)
![projek22b](https://user-images.githubusercontent.com/50059165/57581734-05b60780-74bc-11e9-939e-3e46827fa584.png)
![Uploading projek22c.png…]()

**Comment by andrej4321** [comment]
issue 22

DZIAŁA 

Cel testu:	
Przetestowanie Implementacji enpointu'u statystyk top (wersja z dnia 7.05.19) 
Aplikacja wskazuje najlepsze wyniki które są w bazie danych 

Akcja:
Po uprzednim zainstalowaniu pgadmin  możemy prześledzić całą procedurę 
Wchodzimy po przez konsolę do projektu score-storage.
Następnie wpisujemy polecenie-  gradlew.bat bootRun 
Wykorzystując program Postman używamy   SELECT sum(score) FROM public.sample GROUP BY fk_device_id ORDER BY sum DESC LIMIT 2;
Sprawdzamy poprawność operacji w pgAdmin

Oczekiwania wartość: wyświetlone zostanie wskazana ilość najlepszych wyników 

Wartość testowa: możemy zaobserwować wyświetlenie żądanej ilości najlepszych wyników 

Status: Aplikacja DZIAŁA prawidłowo, szereguje i przekazuje prawidłowo najlepsze wyniki
