### ISSUE TITLE
[ScoreStorage] Implementacja endpoint'u wynik urządzenia

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#23]
DoR:
Dokumentacja API

Co:
Implementacja endpoint'u wynik urządzenia

Dokumentacja API backend znajduje się w katalogu documentation

Dlaczego:
Realizacja

DoD:
aplikacja na żądanie zwraca aktualny wynik urządzenia

**Comment by klkornacki** [comment]
@andrej4321 aby przetestować aplikację należy uruchomić bazę postgres i uruchomić aplikację gradlew.bat bootRun i wywołać w przeglądarce http://localhost:8080/v1/score/my

Powinien wygenerować się json z sumą punktów, następnie należy sprawdzić czy w bazie danych powstała tabela "sample" i suma punktów zgadza się
np. SELECT sum(score) FROM public.sample where fk_device_id = {device id}

Wszystko jest opisane w pliku README.md projektu score-storage

**Comment by Maciaszekanies** [comment]
https://github.com/83997/Projekt_SAN/tree/master/bananaTapChallenge/backend/score-storage

**Comment by andrej4321** [comment]
![projek22](https://user-images.githubusercontent.com/50059165/57581699-5711c700-74bb-11e9-8dba-0466c37b8c3c.png)
![projek22a](https://user-images.githubusercontent.com/50059165/57581700-58db8a80-74bb-11e9-92d3-0295673eda3f.png)
![projek22b](https://user-images.githubusercontent.com/50059165/57581701-5aa54e00-74bb-11e9-8c21-1e57d55fcbff.png)
![projek22c](https://user-images.githubusercontent.com/50059165/57581702-5bd67b00-74bb-11e9-887f-5420a844c901.png)

**Comment by andrej4321** [comment]
issue 23 


DZIAŁA 

Cel testu:	
Przetestowanie Implementacji enpointu'u wynik urządzenia (wersja z dnia 7.05.19) 
Aplikacja sumuje wyniki w przypisane do jednego urządzenia. W tym celu musi wygenerować 
	json z sumą punktów i stworzyć tabelę sample z sumą punktów.  

Akcja:
Po uprzednim zainstalowaniu pgadmin  możemy prześledzić całą procedurę 
Wchodzimy po przez konsolę do projektu score-storage.
Następnie wpisujemy polecenie-  gradlew.bat bootRun 
Wykorzystujemy w program Postman  dzięki metodzie GET i urzyciu   SELECT sum(score) FROM public.sample where fk_device_id={device id}
Sprawdzamy poprawność operacji w pgAdmin.

Oczekiwania wartość: suma wyników dla danego tokenu który został zapisany w bazie danych

Wartość testowa: suma wyników dla danego tokenu który został zapisany w bazie danych

Status: Aplikacja DZIAŁA prawidłowo.
