### ISSUE TITLE
[Analiza] Aktualizacja dokumentacji API

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#25]
Co:
Zaktualizować dokumentację o nowe wytyczne, 

- do endpoint uwierzytelniania dodać pole name, a w odpowiedzi możliwi błąd "the name value is already taken"

- do endpoint score top w odpowiedzi dodać pole name a usunąć id

Dlaczego:
Zmiana projektowa

DoD:
Zostanie zaktualizowana dokumentacja i podbita wersja

**Comment by klkornacki** [comment]
Zmiany w endpoint 
v1/sample/save
Response:
{
    "score": 6576693
}

**Comment by klkornacki** [comment]
Zmiana w endpoint 
v1/score/my
Response:
{
"totalScore": 6576693
}

**Comment by klkornacki** [comment]
Zmiana w endpoint
v1/score/top
Response:
[
    {
        "totalScore": 92655930
    },
    {
        "totalScore": 1669341
    },
    {
        "totalScore": 57070
    }
]

**Comment by klkornacki** [comment]
Zmiana w endpoint
v1/score/top
Params:
"count":10
