### ISSUE TITLE
[Administration] Wdrożenie aplikacji ScoreStore na środowisko TEST

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#27]
DoR:
Działająca wersja aplikacji ScoreStore, przekazana przez @klkornacki 

Co:
Utworzenie środowiska testowego

Dlaczego:
Realizacja

DoD:
Dostarczyć namiary użytkownikowi @SebastianGnas i @klkornacki

**Comment by 83997** [comment]
Usługa bazodanowa wraz z aplikacją uruchomiona na VM (Windows 2012R2, PostgreSQL v11). Trwa nadawanie adresu publiczego do prezentacji w Internecie.
