### ISSUE TITLE
[Administration] Pierwsze wdrożenie aplikacji ScoreStore na środowisko TEST (Actuator)

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#29]
DoR:
Działająca wersja aplikacji ScoreStorage z health check, przekazana przez @klkornacki

Co:
Utworzenie środowiska testowego i uruchomienie aplikacji score-storage
Dokumentacja projektu znajduje się w pliku README.md projektu score-storage

Dlaczego:
Realizacja

DoD:
Aplikacja po wywołaniu http://{ip}:8082/ops/health powinna zwrócić jsona "status" : "UP"
Aplikacja po wywołaniu http://{ip}:8080/v1/token/generate powinna zwrócić token i zapisać rekord do tabeli "device"

Dostarczyć namiary użytkownikowi @SebastianGnas ,@klkornacki i @andrej4321

**Comment by 83997** [comment]
Serwer wystawiony pod:
http://51.83.40.164:8080
lub po nazwie:
http://vps690962.ovh.net:8080

Sprawdzenie czy serwer z usługą działa: http://vps690962.ovh.net:8082/ops/health
Jak działa to serwis zwróci "up"

**Comment by andrej4321** [comment]
issues 29
DZIAŁA  


![TapBanana-service_up](https://user-images.githubusercontent.com/50059165/58377990-7ca6d200-7f8b-11e9-9133-f913161d9b4c.PNG)
