### ISSUE TITLE
[ScoreStorage] Aktualizacja do dokumentacji API v2

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#35]
DoR:
Dokumentacja API v2

Co:
Aktualizacja do dokumentacji API v2

Dokumentacja API v2 backend znajduje się w katalogu documentation

Dlaczego:
Realizacja

DoD:
Endpointy są aktualne względem dokumentacji API v2

**Comment by klkornacki** [comment]
Należy przetestować wszystkie endpoint'y które uległy zmianom

**Comment by andrej4321** [comment]
issue 35 

DZIAŁA
