### ISSUE TITLE
[ScoreStorage] Endpoint samplowania nie nadaje punktów

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#36]
CO:
Nie nadaje punktów przy małej ilości kliknięć w stosunku do dużych jednostek czasu.
Przy większej ilości kliknięć lub krótkim czasie gry błąd nie występuje.

Szczegóły w : https://github.com/83997/Projekt_SAN/issues/21

Dlaczego:
Testy manualne

DoD:
Aplikacja nadaje punkty przy małej ilości kliknięć

**Comment by klkornacki** [comment]
Gotowe do testów

**Comment by klkornacki** [comment]
@andrej4321 Gotowe do testów

**Comment by andrej4321** [comment]
Poprawki występujące w issues 21 zostały naprawione. 
Nawet mała ilość kliknięć prowadzi do nadawania punktów.
