### ISSUE TITLE
Utworzenie diagramu bazy danych aplikacji backend

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#4]

**Comment by Maciaszekanies** [comment]
CO:
Zostanie utworzony diagram bazy danych aplikacji backend
przykład: https://www.lucidchart.com/pages/templates/er-diagram/dbms-er-diagram-template

DLACZEGO:
Analiza

DoD:
Dokument w formacie pdf zostanie dostarczony do repozytorium do katalogu documentation, nazwa pliku diagram-db-v1.pdf

**Comment by mdabrowskiii** [comment]
Pull request do weryfikacji :
https://github.com/83997/Projekt_SAN/pull/12

**Comment by klkornacki** [comment]
- Raczej occuredOn a nie accuredOn
- Count z małej
- Token z małej
- Created z małej
- Status z małej
- Relacja bez strzałki
- Relacja powinna opisać "Many to one"
