### ISSUE TITLE
Utworzenie dokumentacji API (wymiana danych w JSON)

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#6]

**Comment by Maciaszekanies** [comment]
CO:
Zostanie utworzony dokument opisujący API aplikacji backend (wymiana danych w JSON)
przykład: https://gist.github.com/iros/3426278

DLACZEGO:
Analiza

DoD:
Dokument w formacie md zostanie dostarczony do repozytorium do katalogu documentation, nazwa pliku api-rest-v1.md

**Comment by klkornacki** [comment]
- W tym dokumencie powinny być opisane wszystkie endpoint'y potrzebne do realizacji
- Najlepiej w formacie tabeli, tabela na endpoint
- Potrzebne endpoint'y to np. 
1. v1/token/generate
2. v1/sample/save
3. v1/score/get
4. v1/score/my
