### ISSUE TITLE
Utworzenie diagramu Kontekstu

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#8]
CO:
Zostanie utworzony diagram Kontekstu
https://c4model.com/

DLACZEGO:
Analiza

DoD:
Diagram w formacie pdf zostanie dostarczony do repozytorium do katalogu documentation, nazwa pliku diagram-c4-context-v1.pdf

**Comment by klkornacki** [comment]
- Baza danych powinna być oznaczona jako symbol bazy danych
- Strzałki w stronę, kto inicjuje połączenie
- Dokumentacja powinna być po Angielsku
- Nazwa "aplikacja backend" nic nie mówi, czym zajmuje się serwis. Proponuje nazwę np. Serwis ScoreStorageApp
