### ISSUE TITLE
Inicjacja projektu backend - utworzenie struktury projektu

### ISSUE THREAD

**Issue by Maciaszekanies** [83997/Projekt_SAN#9]
CO:
Zostanie utworzony projekt aplikacji Java SpringBoot

DLACZEGO:
Realizacja

DoD:
Kod zostanie dostarczony do repozytorium do katalogu backend

**Comment by klkornacki** [comment]
Pull request do weryfikacji https://github.com/83997/Projekt_SAN/pull/11
